val appCompileSdkVersion by extra(35)
val appTargetSdkVersion by extra(34)
val appMinSdkVersion by extra(24)
val appJdkVersion by extra(21)
val appVersionCode by extra(1)
val appVersionName by extra("1.0")