name: Android Build Environment

description: Configure Java/Gradle/Android SDK and run shared CI quality guards.

inputs:
  setup-android-sdk:
    description: Whether to install Android SDK platform-tools.
    required: false
    default: "false"
  android-packages:
    description: Android SDK packages to install when setup-android-sdk is true.
    required: false
    default: "platform-tools"
  run-gradle-stability-check:
    description: Whether to run verify_gradle_stability.sh.
    required: false
    default: "true"
  run-workflow-quality-check:
    description: Whether to run verify_ci_workflow_quality.sh.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: "21"

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Set up Android SDK
      if: ${{ inputs.setup-android-sdk == 'true' }}
      uses: android-actions/setup-android@v3
      with:
        packages: ${{ inputs.android-packages }}

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Verify Gradle stability
      if: ${{ inputs.run-gradle-stability-check == 'true' }}
      shell: bash
      run: bash scripts/quality/verify_gradle_stability.sh

    - name: Verify CI workflow quality guardrails
      if: ${{ inputs.run-workflow-quality-check == 'true' }}
      shell: bash
      run: bash scripts/quality/verify_ci_workflow_quality.sh
